datadog_checks_base: fix orjson bug
* Fixes `AttributeError: module 'orjson' has no attribute 'JSONEncoder'` when importing `datadog_checks.base.utils.db.statement_samples` where `orjson` is installed.
* Add `datadog_checks_base` `json` dependency to postgres tests so we're actually testing orjson correctly